# Generated by Django 6.1 on 2026-08-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_postgres_helpers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="status",
            field=models.CharField(
                choices=[
                    ("RESERVED", "Reserved"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="RESERVED",
                max_length=20,
            ),
        ),
    ]
